In [1]:
#import packages
import numpy as np

In [2]:
# gene expression matrix
G = np.array([[1,2,3,3],[3,1,9,4],[1,4,3,5]])

### A

In [3]:
# Find the cell with the largest expression of gene 2
np.argmax(G[:,1]) + 1

3

### B

In [4]:
# Which gene is the  most highly expressed in cell 2
np.argmax(G[1,:]) + 1

3

### C

In [5]:
# i. Find rank of G
np.linalg.matrix_rank(G)

2

ii. The rank of the matrix is an indication of the span of its dimensionality.

### D

In [6]:
# i. & ii. Find average expression of the genes
gene_avg = np.mean(G, axis=0)
gene_avg

array([1.66666667, 2.33333333, 5.        , 4.        ])

In [7]:
np.argsort(gene_avg)

array([0, 1, 3, 2])

In [8]:
vT = np.array([1/3, 1/3, 1/3])  # i.
np.matmul(vT, G)

array([1.66666667, 2.33333333, 5.        , 4.        ])

In [9]:
# iii. Get the two highest expressed genes
P = np.array([[0, 0, 1, 0], [0, 0, 0, 1]])
# P = np.array([[0, 0], [0, 0], [1, 0], [0, 1]])
# np.matmul(G, P)
P.T

array([[0, 0],
       [0, 0],
       [1, 0],
       [0, 1]])

### E

In [10]:
from scipy.spatial import distance

# i. compute D for l1, l2, and cos distances
D_l1 = distance.cdist(G, G, metric="cityblock")
print("L1:\n", D_l1)
D_l2 = distance.cdist(G, G, metric="euclidean")
print("L2:\n", D_l2)
D_cos = distance.cdist(G, G, metric="cosine")
print("Cos:\n", D_cos)

L1:
 [[ 0. 10.  4.]
 [10.  0. 12.]
 [ 4. 12.  0.]]
L2:
 [[0.         6.4807407  2.82842712]
 [6.4807407  0.         7.07106781]
 [2.82842712 7.07106781 0.        ]]
Cos:
 [[0.00000000e+00 1.13054633e-01 3.64706819e-02]
 [1.13054633e-01 1.11022302e-16 2.69001000e-01]
 [3.64706819e-02 2.69001000e-01 1.11022302e-16]]


In [11]:
# ii. Closest cells for each metric:
np.argmin(np.where(D_l1>1e-9, D_l1, np.inf))

2

In [12]:
D_l1_argmin = np.argmin(np.where(D_l1>1e-9, D_l1, np.inf))
print("L1 Closest Cells:", 
      np.unravel_index(D_l1_argmin, D_l1.shape))
D_l2_argmin = np.argmin(np.where(D_l2>1e-9, D_l2, np.inf))
print("L2 Closest Cells:", 
      np.unravel_index(D_l2_argmin, D_l2.shape))
D_cos_argmin = np.argmin(np.where(D_cos>1e-9, D_cos, np.inf))
print("Cosine Closest Cells:", 
      np.unravel_index(D_cos_argmin, D_cos.shape))

L1 Closest Cells: (0, 2)
L2 Closest Cells: (0, 2)
Cosine Closest Cells: (0, 2)


### F

In [13]:
# i. All gene expression inflated
G_inflated = G + 20
# i. compute D for l1, l2, and cos distances
D_l1 = distance.cdist(G_inflated, G_inflated, metric="cityblock")
print("L1:\n", D_l1)
D_l2 = distance.cdist(G_inflated, G_inflated, metric="euclidean")
print("L2:\n", D_l2)
D_cos = distance.cdist(G_inflated, G_inflated, metric="cosine")
print("Cos:\n", D_cos)

L1:
 [[ 0. 10.  4.]
 [10.  0. 12.]
 [ 4. 12.  0.]]
L2:
 [[0.         6.4807407  2.82842712]
 [6.4807407  0.         7.07106781]
 [2.82842712 7.07106781 0.        ]]
Cos:
 [[0.         0.00535137 0.00090213]
 [0.00535137 0.         0.0098573 ]
 [0.00090213 0.0098573  0.        ]]


The only distance function that is affected by the "inflated" (scalar additive) gene counts is the cosine similarity.

This makes sense, as the L1 and L2 are distances of *difference*, and the *difference* of two vectors would remain the same if their values were increased by an additive scalar. 

The Cosine similarity metric is a function of vector *magnitude*, which is changed by additive scalars.

### G

In [14]:
G_scaled = G / np.max(G)
# i. compute D for l1, l2, and cos distances
D_l1 = distance.cdist(G_scaled, G_scaled, metric="cityblock")
print("L1:\n", D_l1)
D_l2 = distance.cdist(G_scaled, G_scaled, metric="euclidean")
print("L2:\n", D_l2)
D_cos = distance.cdist(G_scaled, G_scaled, metric="cosine")
print("Cos:\n", D_cos)

L1:
 [[0.         1.11111111 0.44444444]
 [1.11111111 0.         1.33333333]
 [0.44444444 1.33333333 0.        ]]
L2:
 [[0.         0.7200823  0.31426968]
 [0.7200823  0.         0.7856742 ]
 [0.31426968 0.7856742  0.        ]]
Cos:
 [[0.00000000e+00 1.13054633e-01 3.64706819e-02]
 [1.13054633e-01 2.22044605e-16 2.69001000e-01]
 [3.64706819e-02 2.69001000e-01 0.00000000e+00]]


Related to question F, we can see that the invariance of cosine similarity to vector scaling is related to it being a function of vector *magnitude*. Changing the magnitude of a vector by some scaling process will not change its angle relationship to another vector (even if the other vector wasn't scaled). 

However, changing the *magnitude* of two vectors does indeed change their distance relationships to one another. This is easiest to see when plotting two simple unit vectors that are changed either by scaling or addition.