# 746. Min Cost Climbing Stairs

Given a list of costs, find the minimum cost to reach the end of the list. 

Rules:
1. You can either start at index 0 or 1 in the array
2. You an take one or two steps at a time.


**Start: 16:10**

**End: 16:22**

### Planning
This problem is similar to the climbing stairs problem from yesterday, but I don't think
that the solution is quite as simple. 

Can we find the cheapest cost in a single sweep up the stairs?

I wonder if we can find the solution to this problem by taking 1 or two steps up the
array and create a running tally of the array.

Steps:
1. Create a path_cost array of length n + 1
2. Set path_cost[[0, 1]] = cost[[0, 1]]
3. Iterate over each step of the arrays. At each step, add whichever of the i-1 or i-2 is cheapest
to the current cost.

In [109]:
def find_min_cost(cost):
    # Set up the prices array
    prices = cost[:2] + [0] * (len(cost)-1)

    # starting at the second step of the cost array, add the cheapest of the
    # previous two steps and the current cost
    for i in range(2, len(cost)+1):
        prices[i] = min(prices[i-1], prices[i-2])
        if i < len(cost):
            prices[i] += cost[i]
        
    return prices[-1]

cost = [1,100,1,1,1,100,1,1,100,1]
find_min_cost(cost)

6

### Afterthoughts
**Stats**
Runtime
36 ms
Beats
95.90%
Memory
13.5 MB
Beats
54.7%

I'm very happy with this implementation. For fun, I want to try to re-implement it
with only three int variables rather than a list of variables.

In [111]:
def find_min_cost_mem(cost):
    prev_cost, prev2_cost = cost[1], cost[0]
    
    for i in range(2, len(cost)):
        price = min(prev_cost, prev2_cost) + cost[i]
        prev2_cost = prev_cost
        prev_cost = price
        
    return min(prev_cost, prev2_cost)

cost = [1,100,1,1,1,100,1,1,100,1]
find_min_cost(cost)

6

# 62. Unique Paths
Given a top-left starting point on an `m x n` grid (`m = rows`, `n = columns`), find the number
of unique paths that you can take to get to the bottom-right corner.

One can only move one tile down or right at any given iteration.

**Start: 16:31**

**End: 17:08**

### Planning
This problem can be tackled in a brute force manner using recursion. 

Using recursion, we would start at the first tile and call the function with a row increment and then a column
increment, if those increments remained in bounds. We would have a running "paths" tally
that would keep track of how many different calls to the function reached the bottom-right corner
of the grid.

However, leetcode tags this problem with a dynamic approach, so I will try to solve it without using recursion.

Ok - instead, here is my second line of thought. 

Can we instead take an iterative approach to measure the unique number of ways
that individual tiles can be reached?

The bottom-left and top-right cells can only be reached through one unique
path. I'm not sure if this is leading me anywhere, though.

Maybe we can take an approach where we start from the bottom right corner, and we add
up the number of *options* that we have from that square that would lead us towards
the bottom right corner. 

Steps:
1. start at the bottom right corner in an empty array of size `m x n`, set that value to 1.
2. Stepping from right to left, bottom to top, in the empty grid, add all values to the right and below to the current square.
3. Return the value at the top left


In [141]:
import numpy as np
def unique_paths(m, n):
    # create the empty path grid, set bottom right as 1
    path_grid = [[0] * n for _ in range(m)]
    path_grid[-1][-1] = 1

    # iterate over the entire grid from right to left, bottom, to top
    # add the number of unique ways that the bottom right square can be reached
    # by looking at the grids to the bottom and right. There is only one
    # way to get to bottom right from the bottom right - 1, so start there.
    for r in range(m-1, -1, -1):
        for c in range(n-1, -1, -1):
            if r + 1 < m:
                path_grid[r][c] += path_grid[r+1][c]
            if c + 1 < n:
                path_grid[r][c] += path_grid[r][c+1]
    
    print(np.array(path_grid))
    return path_grid[0][0]

m, n = 8, 8
unique_paths(m, n)

[[3432 1716  792  330  120   36    8    1]
 [1716  924  462  210   84   28    7    1]
 [ 792  462  252  126   56   21    6    1]
 [ 330  210  126   70   35   15    5    1]
 [ 120   84   56   35   20   10    4    1]
 [  36   28   21   15   10    6    3    1]
 [   8    7    6    5    4    3    2    1]
 [   1    1    1    1    1    1    1    1]]


3432

### Afterthoughts:
**Stats:**
Runtime
36 ms
Beats
36.12%
Memory
13.5 MB

My approach worked well, but it didn't seem to *perform* well in comparison to other approaches.

I wonder if rather than creating an entire array for this whether we could use fewer variables?

Instead, try an approach where only one row is used at a time.

In [161]:
def unique_paths_mem(m, n):
    paths = [1] * n
    for _ in range(1, m):
        for r in range(1, n):
            paths[r] += paths[r-1]
        print(paths)
    
    return paths[-1]

m, n = 3, 7
unique_paths_mem(m, n)

[1, 2, 3, 4, 5, 6, 7]
[1, 3, 6, 10, 15, 21, 28]


28

**Stats:**
Runtime
35 ms
Beats
39.60%
Memory
13.2 MB
Beats
*88.53%* 

Much better with memory. Not sure about the runtime?

Seems like the faster solutions are solving the problem with a pure equation.

`